version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: meowStack_app
    volumes:
      - ".:/var/www/html"
    working_dir: /var/www/html
    networks:
      - meowStack_internal
      - meowStack_external
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www/html
    ports:
      - "8089:80"
    volumes:
      - ".:/var/www/html"
    networks:
      - meowStack_external
#  phpunit:
#    container_name: meowStack_phpunit
#    build:
#      context: .
#      dockerfile: docker/phpunit/Dockerfile
#    working_dir: /var/www/html
#    volumes:
#      - "./:/var/www/html/"
#    networks:
#      - meowStack_external
  mailhog:
    container_name: meowStack_mailhost
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025"
      - "8028:8025"
    networks:
      - meowStack_external
  db:
    image: mysql:5.7
    container_name: meowStack_db
    build:
      context: docker
      dockerfile: database/Dockerfile
    ports:
      - "3379:3306"
    volumes:
      - "./docker/db:/var/lib/mysql"
    networks:
      - meowStack_internal
networks:
  meowStack_internal:
    internal: true
  meowStack_external:
    external:
      name: meowStack_external
